
database: &common_database
  host: db.example.net
  port: 3306
  user: sird
  password: mypassword
  name: mydb
  enabled: true
  legacy: yes

database_new: *common_database

prod_db:
    <<: *common_database
    host: prod-db.example.net
    password: myprodpassword


dev_db:
    <<: *common_database
    host: hocalhost
    password: password  
